import express from 'express';
import bodyParser from 'body-parser';
import dotenv from 'dotenv';

import router from './routes';

dotenv.load();

// const cloudinary = require('cloudinary').v2;

// // console.log(cloudinary.config());
// // cloudinary.uploader.upload(
// //   './UI/img/PDP.jpg',
// //   {
// //     tags: 'basic_sample',
// //   },
// //   (err, image) => {
// //     console.log();
// //     console.log('** File Upload');
// //     if (err) {
// //       console.warn(err);
// //     }
// //     console.log(`* public_id for the uploaded image is generated by Cloudinary's service.`);
// //     console.log(`* ${image.public_id}`);
// //     console.log(`* ${image.url}`);
// //   },
// // );

const app = express();

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));

app.get('/api/v1/', (req, res) => {
  res.status(200).send({
    message: 'Welcome to politico',
  });
});

app.get('/', (req, res) =>
  res.status(200).send({
    message: 'Welcome to politico',
  }),
);

app.use('/api/v1/', router);

app.listen(3000);
/* eslint-disable-next-line no-console */
console.log('app running on port ', 3000);

export default app;
